/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _LOG_RPC_H_RPCGEN
#define _LOG_RPC_H_RPCGEN

#define RPCGEN_VERSION	199506

#include <rpc/rpc.h>


struct log_data {
	char *usuario;
	char *operacion;
	char *fichero;
};
typedef struct log_data log_data;
#ifdef __cplusplus
extern "C" bool_t xdr_log_data(XDR *, log_data*);
#elif __STDC__
extern  bool_t xdr_log_data(XDR *, log_data*);
#else /* Old Style C */
bool_t xdr_log_data();
#endif /* Old Style C */


#define LOG_PROG ((rpc_uint)0x20000001)
#define LOG_VERS ((rpc_uint)1)

#ifdef __cplusplus
#define LOG_OPERACION ((rpc_uint)1)
extern "C" int * log_operacion_1(struct log_data *, CLIENT *);
extern "C" int * log_operacion_1_svc(struct log_data *, struct svc_req *);

#elif __STDC__
#define LOG_OPERACION ((rpc_uint)1)
extern  int * log_operacion_1(struct log_data *, CLIENT *);
extern  int * log_operacion_1_svc(struct log_data *, struct svc_req *);

#else /* Old Style C */
#define LOG_OPERACION ((rpc_uint)1)
extern  int * log_operacion_1();
extern  int * log_operacion_1_svc();
#endif /* Old Style C */

#endif /* !_LOG_RPC_H_RPCGEN */
