/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _LOG_RPC_H_RPCGEN
#define _LOG_RPC_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct log_data {
	char *usuario;
	char *operacion;
	char *fichero;
};
typedef struct log_data log_data;

#define LOG_PROG 0x20000001
#define LOG_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define LOG_OPERACION 1
extern  int * log_operacion_1(struct log_data *, CLIENT *);
extern  int * log_operacion_1_svc(struct log_data *, struct svc_req *);
extern int log_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define LOG_OPERACION 1
extern  int * log_operacion_1();
extern  int * log_operacion_1_svc();
extern int log_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_log_data (XDR *, log_data*);

#else /* K&R C */
extern bool_t xdr_log_data ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_LOG_RPC_H_RPCGEN */
