/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "log_rpc.h"

bool_t
xdr_log_data(XDR *xdrs, log_data *objp)
{

	if (!xdr_string(xdrs, &objp->usuario, 256))
		return (FALSE);
	if (!xdr_string(xdrs, &objp->operacion, 256))
		return (FALSE);
	if (!xdr_string(xdrs, &objp->fichero, 256))
		return (FALSE);
	return (TRUE);
}
